### ISSUE TITLE
Dependencies: Move away from Rocket to Actix

### ISSUE THREAD

**Issue by valeriansaliou** [valeriansaliou/constellation#18]
See PR https://github.com/valeriansaliou/vigil/pull/72 from Vigil, with migration code. Should be quite similar in Constellation.

**Comment by valeriansaliou** [comment]
Once moved, update all build instructions & scripts as nightly will not be required anymore.

**Comment by kination** [comment]
@valeriansaliou is there some reason you want to change?

**Comment by valeriansaliou** [comment]
@djKooks yes, for now this is due to the fact that Rocket requires the `nightly` toolchain, which prevents Constellation from compiling on `stable`, which is a hassle.

**Comment by kination** [comment]
@valeriansaliou is there some reason you've choose `actix`? Cause there are several web framework stuff, such as `tide`, `axum` (it is just curiosity 🤔 )

**Comment by valeriansaliou** [comment]
Done in `v1.14.0`.
