### ISSUE TITLE
there is nothing to install in `rusqlite v0.28.0

### ISSUE THREAD

**Issue by miguelgargallo** [valeriansaliou/constellation#24]
Compiling rusqlite v0.13.0
error[E0119]: conflicting implementations of trait `std::convert::From<&_>` for type `types::to_sql::ToSqlOutput<'_>`
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.13.0/src/types/to_sql.rs:26:1
   |
18 | impl<'a, T: ?Sized> From<&'a T> for ToSqlOutput<'a>
   | --------------------------------------------------- first implementation here
...
26 | impl<'a, T: Into<Value>> From<T> for ToSqlOutput<'a> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `types::to_sql::ToSqlOutput<'_>`
   |
   = note: downstream crates may implement trait `std::convert::From<&_>` for type `types::value::Value`

For more information about this error, try `rustc --explain E0119`.
error: could not compile `rusqlite` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `constellation-server v1.14.1`, intermediate artifacts can be found at `/tmp/cargo-installvH7JDJ`
[user@computer ~]$

**Comment by miguelgargallo** [comment]
Updating crates.io index
  Downloaded rusqlite v0.28.0
  Downloaded 1 crate (137.5 KB) in 0.37s
error: there is nothing to install in `rusqlite v0.28.0`, because it has no binaries
`cargo install` is only for installing programs, and can't be used with libraries.
To use a library crate, add it as a dependency in a Cargo project instead.

**Comment by valeriansaliou** [comment]
Hey there! For now, Constellation needs to be installed from a local source, which patches `rustqlite` w/ a previous version, that is:

```
git pull git@github.com:valeriansaliou/constellation.git
cd constellation
cargo install --path ./
```

That way, the following patch will be applied: https://github.com/valeriansaliou/constellation/blob/master/Cargo.toml#L50

**Comment by valeriansaliou** [comment]
Note that you could also use a pre-built binary that works out of the box: https://github.com/valeriansaliou/constellation/releases

**Comment by miguelgargallo** [comment]
Thanks for you time, and Merry Christmas 🎄
