### ISSUE TITLE
CAA Record

### ISSUE THREAD

**Issue by Berndinox** [valeriansaliou/constellation#25]
Hey there, i'm about to write a template for constellation to be used on fly.io!
_I tried PowerDNS first but using a Database Backend AND GeoIP Feature does not work...._

Constellation looks really very promising, however one Record Type i miss is CAA.
Adding the record type would be really great!

I will publish the fly.io template once finished (Global Distributed with Anycast-IP for cheap)

**Comment by paulocoghi** [comment]
It would be interesting to have a compatibility table to show supported and unsupported DNS record types.

**Comment by valeriansaliou** [comment]
Sorry to be late to this. I’ll implement both of what you suggested after the Async rework of constellation, that is, within the week/next week.

**Comment by valeriansaliou** [comment]
@Berndinox this is to let you know that CAA records are now fully supported in Constellation (on the master branch). CNAME flattening also supports CAA records now.

As @paulocoghi suggested, a record type support matrix table has been also added to the README: https://github.com/valeriansaliou/constellation?tab=readme-ov-file#supported-record-types

Thanks you two!
